// import Head from "next/head";
// import Link from "next/link";

// import { api } from "~/utils/api";

// export default function Home() {
// 	const hello = api.post.hello.useQuery({ text: "from tRPC" });

// 	return (
// 		<>
// 			<Head>
// 				<title>Create T3 App</title>
// 				<meta content="Generated by create-t3-app" name="description" />
// 				<link href="/favicon.ico" rel="icon" />
// 			</Head>
// 			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#aaa3b5] to-[#c6c6d3]">
// 				<div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
// 					<h1 className="font-extrabold text-5xl text-white tracking-tight sm:text-[5rem]">
// 						Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
// 					</h1>
// 					<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
// 						<Link
// 							className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
// 							href="https://create.t3.gg/en/usage/first-steps"
// 							target="_blank"
// 						>
// 							<h3 className="font-bold text-2xl">First Steps →</h3>
// 							<div className="text-lg">
// 								Just the basics - Everything you need to know to set up your
// 								database and authentication.
// 							</div>
// 						</Link>
// 						<Link
// 							className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
// 							href="https://create.t3.gg/en/introduction"
// 							target="_blank"
// 						>
// 							<h3 className="font-bold text-2xl">Documentation →</h3>
// 							<div className="text-lg">
// 								Learn more about Create T3 App, the libraries it uses, and how
// 								to deploy it.
// 							</div>
// 						</Link>
// 					</div>
// 					<p className="text-2xl text-white">
// 						{hello.data ? hello.data.greeting : "Loading tRPC query..."}
// 					</p>
// 				</div>
// 			</main>
// 		</>
// 	);
// }




import React from 'react'
import CapabilitiesSection from '~/components/home/CapabilitiesSection'
import CTASection from '~/components/home/CTASection'
import ExpertiseSection from '~/components/home/ExpertiseSection'
import HeroSection from '~/components/home/HeroSection'
import IndustriesSection from '~/components/home/IndustriesSection'

const index = () => {
  return (
	<div>
	  <HeroSection></HeroSection>
	  <ExpertiseSection></ExpertiseSection>
	  <CapabilitiesSection></CapabilitiesSection>
	  <IndustriesSection></IndustriesSection>
	  <CTASection></CTASection>
	</div>
  )
}

export default index
